version: '3.5'
services:
    database:
        image: docker-class
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: Mbade
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            [db-volume:/var/lib/mysql]